# Generated by Django 3.1.3 on 2020-11-18 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Generic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PharmaCompare.drug')),
            ],
        ),
        migrations.AddField(
            model_name='drug',
            name='gen_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PharmaCompare.generic'),
        ),
    ]
