# Generated by Django 3.1.3 on 2020-11-18 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PharmaCompare', '0003_auto_20201118_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='gen_id',
            new_name='generic',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='drug_id',
            new_name='drug',
        ),
    ]
