# Generated by Django 3.1.3 on 2020-11-18 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PharmaCompare', '0004_auto_20201118_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='desc',
            new_name='descriptiion',
        ),
        migrations.RenameField(
            model_name='drug',
            old_name='type',
            new_name='drug_type',
        ),
    ]
