# Generated by Django 3.1.3 on 2020-11-19 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_store_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('drug_id', models.AutoField(primary_key=True, serialize=False)),
                ('drug_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('drug_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Generic',
            fields=[
                ('generic_id', models.AutoField(primary_key=True, serialize=False)),
                ('generic_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, default=9.99)),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharma.drug')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.store')),
            ],
        ),
        migrations.AddField(
            model_name='drug',
            name='generic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharma.generic'),
        ),
    ]
